### ISSUE TITLE
Page number not working

### ISSUE THREAD

**Issue by Inartus** [arbor-education/sis-sdk-php#21]
File Query.php line 226 incorrectly sets $queryString['page'] when it should set $queryString['page-number']
I have tested this with a local modification.

**Comment by crees** [comment]
Seems to be fixed in 19807c4.

**Comment by georgemilojevic** [comment]
This was fixed in the [4.0.2](https://github.com/arbor-education/sis-sdk-php/releases/tag/4.0.2)
