### ISSUE TITLE
Setting the orderProperty does not do anything

### ISSUE THREAD

**Issue by Inartus** [arbor-education/sis-sdk-php#22]
The order property is not referenced when building the queryString so is effectively ignored.
Because of this, it is not possible to sort data via the SKD.

**Comment by crees** [comment]
Also appears to be fixed in 19807c4 :)

**Comment by georgemilojevic** [comment]
This was fixed in the [4.0.2](https://github.com/arbor-education/sis-sdk-php/releases/tag/4.0.2)
